# æ”¹è¡Œã‚ã‚Šã®è¦‹ã‚„ã™ã„ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆ
add_newline = true

# ã‚¨ãƒ‡ã‚£ã‚¿ãƒ¼ã®è£œå®Œã‚’è¨­å®šã‚¹ã‚­ãƒ¼ãƒã«åˆã‚ã›ã¦å–å¾—
"$schema" = 'https://starship.rs/config-schema.json'
scan_timeout = 10

# è¨˜å·"â¯"ã‚’è¨˜å·"âœ"ã«ç½®ãæ›ãˆã‚‹
[character]
success_symbol	= '[âœ](bold green)'
error_symbol	= "[âœ—](bold red)"
vicmd_symbol = "[â®](bold yellow)"

[directory]
truncation_length = 3
truncate_to_repo = false
style = "cyan"
#truncation_symbol = "â€¦/"

[git_branch]
symbol = "ïˆ "
format = "[$symbol$branch]($style) "
style = "purple"

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "yellow"

[rust]
symbol = "ğŸ¦€ "
format = '[$symbol$version]($style) '
style = "red"
detect_files = ["Cargo.toml"]

[python]
symbol = "ğŸ "
format = '[$symbol$version (\($virtualenv\))]($style) '
style = "blue"
detect_files = ["pyproject.toml", "requirements.txt", "setup.py"]

[custom.build]
command = "echo ğŸ› ï¸"
detect_files = ["Makefile", "CMakeLists.txt"]
format = "[$symbol]($style) "
symbol = "ğŸ› ï¸"
style = "bold green"

[cmd_duration]
min_time = 500  # 0.5ç§’ä»¥ä¸Šã‹ã‹ã£ãŸå ´åˆã®ã¿è¡¨ç¤º
format = "took [$duration]($style) "
style = "italic dimmed white"

[time]
disabled = true
time_format = "%Y-%m-%d %H:%M:%S"
utc_time_offset = "+9"

# package ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ã‚’ç„¡åŠ¹åŒ–ã—ã¦ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã‹ã‚‰å®Œå…¨ã«éè¡¨ç¤ºã«ã™ã‚‹
[package]
disabled = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$userğŸŒ±]($style) "
disabled = false
show_always = true
