# ã‚¨ãƒ‡ã‚£ã‚¿ãƒ¼ã®è£œå®Œã‚’è¨­å®šã‚¹ã‚­ãƒ¼ãƒã«åˆã‚ã›ã¦å–å¾—
"$schema" = 'https://starship.rs/config-schema.json'
scan_timeout = 10
add_newline = true

# è¨˜å·"â¯"ã‚’è¨˜å·"âœ"ã«ç½®ãæ›ãˆã‚‹
[character]
success_symbol	= '[âœ](bold green)'
error_symbol	= "[âœ—](bold red)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ïˆ "

[time]
disabled = true
time_format = "%Y-%m-%d %H:%M:%S"
utc_time_offset = "+9"

# package ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ã‚’ç„¡åŠ¹åŒ–ã—ã¦ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã‹ã‚‰å®Œå…¨ã«éè¡¨ç¤ºã«ã™ã‚‹
[package]
disabled = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$userğŸŒ±]($style) "
disabled = false
show_always = true
